### ISSUE TITLE
website seems down - any other way to download compiled addon

### ISSUE THREAD

**Issue by lalamax3d** [JPfeP/AddRoutes#11]
Hi, i am on ubuntu 20 , wanted to use 2.93 or 3.0 version.

req: if possible, can you please link release version directly downloadable from github. huge thanks in advance.

Currently, if i download source (zip), rename it to AddRoutes.zip and try to install in blender(2.92 or 2.93) all giving me this error

`
Traceback (most recent call last):
  File "/opt/blender-2.92.0/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/2.92/scripts/addons/AddRoutes-master/__init__.py", line 56, in <module>
    from . import data
  File "/home/user/.config/blender/2.92/scripts/addons/AddRoutes-master/data.py", line 32, in <module>
    from . import g_vars
  File "/home/user/.config/blender/2.92/scripts/addons/AddRoutes-master/g_vars.py", line 22, in <module>
    import rtmidi
ModuleNotFoundError: No module named 'rtmidi'
`
thanks again for any psudo steps guidance / ideas.

**Comment by JPfeP** [comment]
Hello, 
The website is still online. Probably a temporary maintenance operation from my provider ? Don't use the github version that way, it's not self sufficient.

I just put a repacked 0.33 version on my web site which should work with Blender 3.1 as well for Linux (Windows and OSX are still limited to Blender 3.0 for now)

Here is the direct link :
http://www.jpfep.net/static/AddRoutes_latest.zip

**Comment by lalamax3d** [comment]
just downloaded latest and tried.
3.0 , works fine, (huge thanks again sir)
3.1, following error log, (may help to sort out). just for ref
`Traceback (most recent call last):
  File "/opt/blender-3.1/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/3.1/scripts/addons/AddRoutes/__init__.py", line 56, in <module>
    from . import data
  File "/home/user/.config/blender/3.1/scripts/addons/AddRoutes/data.py", line 32, in <module>
    from . import g_vars
  File "/home/user/.config/blender/3.1/scripts/addons/AddRoutes/g_vars.py", line 22, in <module>
    import rtmidi
  File "/home/user/.config/blender/3.1/scripts/addons/AddRoutes/rtmidi/__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/user/.config/blender/3.1/scripts/addons/AddRoutes/rtmidi/_rtmidi.cpython-310-x86_64-linux-gnu.so)

`
going to try sorting

**Comment by JPfeP** [comment]
Damned, I built the midi lib for python 3.10 it on my newer ubuntu system Impish "21.10" and probably it's the problem. I am going to try to rebuild it on the 20.04 LTS one that I have instead. I will inform you, I hope today.

**Comment by JPfeP** [comment]
OK, I rebuilt it on Ubuntu 20.04 LTS and put it on the website. You can re-download (same link than above) and re-install the Add-On if you want to try it with Blender 3.1
I hope it will be compatible with many Linux distributions. This has the merit to raise that issue for the future versions. 
Let me know if any problem remains. And thanks for your report.
