### ISSUE TITLE
Cannot enable pluging. Errors pop up.

### ISSUE THREAD

**Issue by TheSeanLavery** [JPfeP/AddRoutes#4]
Using the latest "ready to go" version here. http://www.jpfep.net/pages/addroutes/ on blender 2.82a

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Sean\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\AddRoutes\__init__.py", line 51, in <module>
    from . import ui
  File "C:\Users\Sean\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\AddRoutes\ui.py", line 27, in <module>
    from data import generate_dict
  File "C:\Users\Sean\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\multi-user\libs\replication\replication\data.py", line 15, in <module>
    from .constants import (
ImportError: attempted relative import with no known parent package

**Comment by JPfeP** [comment]
Thank for your report. I wonder what could be the origin of this problem. 

This line: File "C:\Users\Sean\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\multi-user\libs\replication\replication\data.py"
... is showing a different path than :
C:\Users\Sean\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\AddRoutes\ui.py
 
It would mean that another module is called data.py in another add-on and Blender tries to import it. That's pretty unexpected. 

As you could see on the github sources there is no replication/replication/data.py path in Addroutes.

**Comment by JPfeP** [comment]
It seems that there is indeed a conflict with this file:
https://gitlab.com/slumber/replication/-/blob/master/replication/data.py

...which belongs to the multi-user add-on:
https://gitlab.com/slumber/multi-user
https://blenderartists.org/t/multi-user/1187118

I am going to study a proper way to fix that. Changing its name in AddRoutes is a simple solution but it's a little bit frightening that nameclashes can occur that way. Still puzzled...

**Comment by TheSeanLavery** [comment]
Cool! Please let me know when this is available.

Is there a quick fix I can try on my end?

**Comment by JPfeP** [comment]
It's not that difficult but might affect several files, mostly in ui.py:
"from data import generate_dict" has to be replaced by  "from .data import generate_dict"

I apologize for the delay as I had some Pandora's box to open/close in the meanwhile. I am rewriting the osc and midi device configuration.

**Comment by JPfeP** [comment]
At last, the v0.30 is ready with the bug fix: 
http://www.jpfep.net/addroutes-v030/

Please let me know if it solves the pbm.

**Comment by TheSeanLavery** [comment]
Awesome. Thank you so much for fixing the problem.

I got the plugin working after a bit of fiddling around. Ableton being open on start prevented the keyboard from being configurable. And opening Ableton afterward, I can't get the midi to work in there too. Might just be a limitation of midi though?

**Comment by df-0** [comment]
I think I may be getting a similar issue using v0.32 on Blender 2.93.0 and 2.92

```Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\AddRoutes\__init__.py", line 56, in <module>
    from . import data
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\AddRoutes\data.py", line 32, in <module>
    from . import g_vars
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\AddRoutes\g_vars.py", line 22, in <module>
    import rtmidi
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\AddRoutes\rtmidi\__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
ModuleNotFoundError: No module named 'rtmidi._rtmidi'

```

Any ideas?
